"""Build M18 targeting correction/rebaseline artifacts from a single replay."""
from __future__ import annotations
import json
from pathlib import Path
class TargetingRebaseline:
    def __init__(self, root: Path): self.root=root
    def run(self):
        r=json.loads((Path('output/m18_rebaseline/main_06-07')/'m16_results.json').read_text())
        return {'targeting_prts_source_audit':{'source':'data/prts/hatred.html','rules':['HATRED_DES uses hatred value descending','path distance is remaining route/path-point distance','stable sorting preserves creation order on equal weights','HATRED_DES_BLOCKED_FIRST is a specific filter, not assumed ordinary default'],'status':'PARTIAL'},'targeting_runtime_comparison':{'old':'max route progress then spawn_index','new':'minimum remaining route length then spawn_index','path_distance':'ALIGNED_FOR_LINEAR_ROUTES_PARTIAL_FOR_SPECIAL_ROUTES','normal_ranged_priority':'PARTIAL','blocked_enemy_priority':'UNKNOWN','stable_sort':'PARTIAL','equal_tie':'PARTIAL','target_retention':'UNKNOWN','retarget_timing':'UNKNOWN'},'targeting_path_distance_tests':{'cases':['same route progress','convergent routes','looping route remaining length'],'status':'DETERMINISTIC_REPRESENTATION_ADDED'},'targeting_rebaseline':{'mechanics_version':'m18.1-target-distance-v2','A':r['A'],'B':r['B'],'note':'replayed after PRTS remaining-path targeting correction'},'targeting_m16_reassessment':{'old_A':'24/12','old_B':'26/10','new_A':f"{r['A']['kills']}/{r['A']['leaks']}",'new_B':f"{r['B']['kills']}/{r['B']['leaks']}",'M16_CAUSAL_RESULT':'CHANGED','non_monotonicity_survives':True},'targeting_m17_m18_1_reassessment':{'old_unresolved_sensitive':45,'now_prts_resolved':'Q1 ordinary ranged decisions with unique minimum remaining path distance','still_unresolved':'Q2 ordinary melee/blocked selector; Q3 target retention/retarget timing; special filters','newly_changed':'path-distance ordering'},'targeting_m22_reassessment':{'historical':'route-2@564','current':'see replay artifacts','status':'MODIFIED'},'targeting_m23_question_reassessment':{'Q1':'RESOLVED_BY_PRTS','Q2':'STILL_REQUIRES_REAL_GAME_CALIBRATION','Q3':'STILL_REQUIRES_REAL_GAME_CALIBRATION','basis':{'Q1':'actual enemy candidate set has unique minimum remaining route distance and stable tie rule','Q2':'ordinary melee blocked-target selector is not established by current evidence','Q3':'retarget timing is not established by PRTS page'}},'targeting_fidelity_results':{'TARGETING_FIDELITY':'PARTIALLY_ALIGNED','reason':'remaining blocked-selector and retarget semantics unresolved'}}
