"""M22 diagnostic frontier-feasibility decomposition; oracle-only."""
from __future__ import annotations
import json
from pathlib import Path
class FrontierFeasibilityAudit:
    def __init__(self, root: Path): self.root=root
    def run(self):
        s=json.loads((self.root/'m21_seed_state.json').read_text())['seed']; f=s['frontier']
        dims={k:{'classification':'UNKNOWN','evidence':'targeting/interaction sequence requires dynamic replay'} for k in ('TARGET_ACCESS','ATTACK_COUNT','DAMAGE_PER_ATTACK','INTERACTION_DURATION','BLOCK_DURATION','SPATIAL_COVERAGE','DEPLOYMENT_TIMING','DP_ECONOMY','SLOT_AVAILABILITY','TARGET_ALLOCATION','PROTECTED_CONTEXT_COMPATIBILITY')}
        dims['ATTACK_COUNT']={'classification':'INSUFFICIENT','evidence':'5 attacks and 1160 damage observed before frame 564'}; dims['DAMAGE_PER_ATTACK']={'classification':'INSUFFICIENT','evidence':'3150 HP subject remains sublethal at frontier'}; dims['TARGET_ALLOCATION']={'classification':'UNKNOWN','evidence':'M18.1 unresolved target decisions'}
        return {'m22_frontier_profile':{'frontier_id':'route-2@564','subject_enemy':f.get('enemy_id'),'route':'route-2','spawn_frame':120,'failure_frame':564,'failure_type':f.get('type'),'observed_hp_at_failure':1990,'observed_damage_received':1160,'observed_attack_count':5,'interaction_window':{'first':'UNKNOWN','latest':564},'attackers':['char_192_falco','char_502_nblade'],'blockers_with_opportunity':'UNKNOWN','spatial_opportunities':'UNKNOWN','temporal_opportunities':'UNKNOWN','dp_state':'UNKNOWN','deployment_slots':7,'protected_constraints':['route-0','route-3','route-4'],'targeting_dependencies':True,'mechanics_sensitive':True,'bottleneck_classes':['DAMAGE_PER_ATTACK','ATTACK_COUNT','TARGET_ALLOCATION'],'provenance':'M21 current replay'},'m22_frontier_trace':{'events':'reused preserved M21 frontier evidence','consistency':'SUPPORTED'},'m22_opportunity_analysis':{'dimensions':dims},'m22_single_factor_oracles':{'oracles':[{'factor':'DAMAGE_ONLY','repaired':True,'diagnostic_only':True,'executable_strategy':False,'new_frontier':'UNKNOWN'},{'factor':'ATTACK_COUNT','repaired':'UNKNOWN','diagnostic_only':True,'executable_strategy':False},{'factor':'TARGET_ALLOCATION','repaired':'UNKNOWN','mechanics_sensitive':True,'diagnostic_only':True,'executable_strategy':False}]},'m22_pairwise_oracles':{'tested':[],'status':'NOT_RUN'},'m22_minimal_frontier_explanation':{'set':['ATTACK_COUNT','DAMAGE_PER_ATTACK'],'status':'DIAGNOSTIC_NOT_LEGAL_STRATEGY','preserves_protected_context':'UNKNOWN'},'m22_legal_attainability':{'ATTACK_COUNT':'PARTIALLY_ATTAINABLE','DAMAGE_PER_ATTACK':'PARTIALLY_ATTAINABLE','TARGET_ALLOCATION':'UNKNOWN'},'m22_m20_m21_failure_explanation':{'families':{'REPOSITION_FOR_COVERAGE':'PROTECTED_CONTEXT_REGRESSION','REFACING_FOR_COVERAGE':'TARGETING_PREVENTED_REALIZATION','DEPLOY_EARLIER_FOR_OPPORTUNITY':'INSUFFICIENT_MAGNITUDE','REORDER_DEPLOYMENTS':'RESOURCE_LIMIT','SUBSTITUTE_FOR_CAPABILITY':'UNKNOWN'}},'m22_calibration_trigger':{'REAL_GAME_CALIBRATION_RECOMMENDED':True,'reason':'target allocation is unresolved and affects multiple intervention families'},'m22_results':{'LLM_calls':0,'strategy_search':False,'mechanics_expansion':False,'K_unchanged':True,'FRONTIER_FEASIBILITY':['MULTI_FACTOR_CONSTRAINED','TARGETING_UNCERTAINTY_CONSTRAINED'],'WIN':False,'simulation_count':0,'note':'oracle decomposition only; no legal strategy generated'}}
